Attempt 2: add replace to root: maybe works but rustc_private doesn't
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.12s
Building stage0 library artifacts (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.07s
Building compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
   Compiling tracing-core v0.1.30 (/home/stypox/Documents/uni/semester_project/rust/src/tools/miri/shim_tracing)
   Compiling rustc_baked_icu_data v0.0.0 (/home/stypox/Documents/uni/semester_project/rust/compiler/rustc_baked_icu_data)
   Compiling rustc_fluent_macro v0.0.0 (/home/stypox/Documents/uni/semester_project/rust/compiler/rustc_fluent_macro)
error[E0463]: can't find crate for `tracing_core`
 --> src/tools/miri/shim_tracing/src/lib.rs:3:1
  |
3 | extern crate tracing_core;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
error: could not compile `tracing-core` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:00:05